version: '3.5'
services:
  app:
    build: .
    container_name: mernstack-vite-template
    command: npm run dev
    image: mernstack-vite-template:latest
    ports:
      - '3000:3000'
      - '5000:5000'
    volumes:
      - .:/app
